### ISSUE TITLE
"SystemError: error return without exception set" when creating App

### ISSUE THREAD

**Issue by gmseabra** [nir/jupylet#24]
Hi,

I'm trying to run jupylet on Windows, with Python 3.9.1. After installing the libraries following the instructions on the docs, if I try to run any example that creates an App I am getting the error:

```
app = App()
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-5-91042f890017> in <module>
----> 1 app = App()

~\Source\Repos\jupylet\jupylet\app.py in __init__(self, width, height, mode, resource_dir, quality, **kwargs)
    236 
    237         shader = set_shader_2d(self.load_program('shaders/sprite.glsl'))
--> 238         shader['projection'].write(glm.ortho(
    239             0, width, 0, height, -1, 1
    240         ))

~\Miniconda3\envs\jupylet\lib\site-packages\moderngl\program_members\uniform.py in write(self, data)
    176         '''
    177 
--> 178         self.mglo.data = data

SystemError: error return without exception set
```
Any idea what could be wrong?

Thank you!

**Comment by nir** [comment]
Hi, jupylet is only compatible with python 3.6, 3.7 or 3.8 since some of its dependencies do not support python 3.9 yet.

If you install the conda distribution of python you can easily setup differnet environments each with a different version of python.

**Comment by nir** [comment]
How did you install it?

**Comment by gmseabra** [comment]
Hi,

Thanks for the fast answer! I had installed in a conda env that I created. By default it created the env with Python 3.9 \o/.

I tried again with a fresh env created with
```
$ conda create -n jupylet python=3.8
```
and follow the remaining instructions, and now it works fine.

Thanks!

**Comment by nir** [comment]
Nice.

Recent pypi packages of Jupylet declare they require python < 3.9 and I "yanked" the older versions in pypi. 

Thanks to your heads up I now see that for some reason pip on python 3.9 just skips the new versions that it cannot install and silently tries to install an older yanked version. Will try to think what to do about it.

Thanks for this report.

**Comment by gmseabra** [comment]
You are welcome. Thank **you** for putting the effort in this package! It is very nice and helpful!

All the best,
Gustavo.
