### ISSUE TITLE
App.run() does not automatically exit / quit 

### ISSUE THREAD

**Issue by sefgit** [nir/jupylet#25]
Hi, thanks for this amazing jupylet.
Installed and now trying the examples to understand how to use jupylet.
On Windows 10, using Python 3.6, I can't close all examples started from IDLE.
The same goes for all examples run on jupyter. When I close the jupyter's browser tabs, all jupylet examples are still running.
The only way to close the examples are thru Task Managers.

Is there any flag to set so that App.run() can automatically exit / quit when its window / display is closed ?
Or maybe "exit/quit event" that needs to be handled ?

Thank you

**Comment by nir** [comment]
Hi, when you close a jupyter tab the python kernel keeps running. This is expected behaviour. To shut it down you need to shutdown the kernel explicitly from the top menu. 

I'll check out behaviour with idle.

Thank you for this report.

**Comment by nir** [comment]
Do you mean that when running in IDLE if you click the top-right red [X] close button of the running game window, it stops but does not close?

**Comment by sefgit** [comment]
Yes, in IDLE it won't stop.

And it would be great if it can stop in JUPYTER too, when tab is closed or with whatever command / event handler.
Thanks

**Comment by sefgit** [comment]
Probably not quite related, but I found after some googling that in  pygame, I have to call **pygame.display.quit()** to exit the application cleanly, i.e. closing its main window.

**Comment by sefgit** [comment]
indeed, this is what I tried and it works for me in IDLE.

```
if __name__ == '__main__':
    app.run(1/30)
    app.window.close()
    print("* DONE") # to verify that app has terminated
```
