### ISSUE TITLE
Any hint for Jupylet to work in voila?

### ISSUE THREAD

**Issue by Fusyong** [nir/jupylet#34]
I want to show Jupylet works in Voila, or Streamlet, or PyWebIO,
but I can not see the canvas of Jupylet in  Voila.
Any advice would be appreciated.

**Comment by nir** [comment]
from a first look at voila it seems that it should work in principle, but I did not try it myself.

Maybe you need to somehow install the ipywidgets and ipyevents jupyter notebook plugins explicitly to voila?

Jupylet relies on these two plugins.

Let me know if it works

**Comment by Fusyong** [comment]
Jupylet can works with [Voila As a Jupyter server extension](https://voila.readthedocs.io/en/stable/using.html#as-a-jupyter-server-extension). But sometime I get the error of `Could not instantiate widget`, and should be OK after refreshing the page. 

Thanks for your great work!
